# Generated by Django 3.0.6 on 2020-05-13 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_content', models.ImageField(upload_to='')),
                ('post_date', models.DateTimeField(verbose_name='date posted')),
                ('postvotes', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respvotes', models.IntegerField(default=0)),
                ('submission_time', models.DateTimeField(verbose_name='date responded')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Post')),
            ],
        ),
    ]
