# Generated by Django 3.0.6 on 2020-05-13 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_title',
            field=models.CharField(default='post title goes here numbnuts', max_length=255),
        ),
    ]
